// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Quraaa.Persistence.Data;

#nullable disable

namespace Quraaa.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608003607_AddLibraries")]
    partial class AddLibraries
    {
    }
}
