using MediatR;
using Microsoft.Extensions.Logging;
using Quraaa.Application.Features.Books.Common;
using Quraaa.Application.Features.Books.Interfaces;
using Quraaa.Application.Features.Libraries.Interfaces;
using Quraaa.Application.Features.Listings.Interfaces;
using Quraaa.Application.Shared.Results;
using Quraaa.Application.Shared.Services;
using Quraaa.Domain.Catalog;
using Quraaa.Domain.Marketplace;
using Quraaa.Domain.Marketplace.Enums;
using Quraaa.Domain.Shared.Exceptions;

namespace Quraaa.Application.Features.Books.Commands.BulkUploadBooks
{
    public sealed class BulkUploadBooksCommandHandler
        : BaseApplicationService<BulkUploadBooksCommandHandler>,
          IRequestHandler<BulkUploadBooksCommand, AppResult<BulkUploadBooksResponse>>
    {
        private readonly IBookRepository _bookRepository;
        private readonly IListingRepository _listingRepository;
        private readonly ILibraryRepository _libraryRepository;
        private readonly IBulkBookStorageService _storageService;

        public BulkUploadBooksCommandHandler(
            IBookRepository bookRepository,
            IListingRepository listingRepository,
            ILibraryRepository libraryRepository,
            IBulkBookStorageService storageService,
            ILogger<BulkUploadBooksCommandHandler> logger,
            IServiceProvider serviceProvider)
            : base(logger, serviceProvider)
        {
            _bookRepository = bookRepository;
            _listingRepository = listingRepository;
            _libraryRepository = libraryRepository;
            _storageService = storageService;
        }

        public Task<AppResult<BulkUploadBooksResponse>> Handle(
            BulkUploadBooksCommand command,
            CancellationToken cancellationToken) =>
            ExecuteAsync<BulkUploadBooksCommand, BulkUploadBooksResponse>(
                command,
                () => ProcessAsync(command, cancellationToken),
                $"{command.Books.Count} book(s) processed.");

        // ─────────────────────────────────────────────────────────────────────────
        // Core pipeline:
        //   0. Resolve the requesting library — fail fast, before any file I/O
        //   1. Deduplicate within the incoming batch (in-memory, O(n))
        //   2. Single DB roundtrip  — find which of the new books already exist
        //   3. Partition            — new books vs. duplicates
        //   4. File I/O             — save files only for genuinely new books
        //   5. Bulk insert          — books + their listings in one SaveChanges
        //                              call, rolls back files on failure
        // ─────────────────────────────────────────────────────────────────────────
        private async Task<BulkUploadBooksResponse> ProcessAsync(
            BulkUploadBooksCommand command,
            CancellationToken cancellationToken)
        {
            // ── Phase 0: Resolve the caller's library ────────────────────────────
            var library = await _libraryRepository.GetApprovedByUserIdAsync(
                command.RequestingUserId, cancellationToken)
                ?? throw new NotFoundException("Library was not found.");

            // ── Phase 1: Intra-batch deduplication ───────────────────────────────
            var (uniqueGroups, batchDuplicates) = DeduplicateWithinBatch(command.Books);

            // ── Phase 2: One DB roundtrip — broad title IN-clause, precise in memory ──
            //
            // Query generated by EF Core + Npgsql:
            //   SELECT "Title", "Author", "Language"
            //   FROM "Books"
            //   WHERE lower("Title") IN ('title1', 'title2', ...)
            //
            // This single query covers all incoming books at once (no N+1).
            // The expression index added by migration AddCaseInsensitiveBookIndexes
            // on lower("Title") makes this lookup fast even on a large catalog.
            var normalizedTitles = uniqueGroups
                .Select(g => BookTextNormalizer.Normalize(g.Metadata.Title))
                .Where(t => t.Length > 0)
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();

            var dbCandidates = await _bookRepository.FindExistingCandidatesAsync(
                normalizedTitles, cancellationToken);

            // Build a precise composite-key set for the final O(1) per-book lookup.
            var existingKeys = dbCandidates
                .Select(c => BookTextNormalizer.CompositeKey(c.Title, c.Author, c.Language))
                .ToHashSet(StringComparer.OrdinalIgnoreCase);

            // ── Phase 3: Partition ────────────────────────────────────────────────
            var newGroups    = new List<BookUploadFileGroup>(uniqueGroups.Count);
            var dbDuplicates = new List<SkippedBookResult>(uniqueGroups.Count);

            foreach (var group in uniqueGroups)
            {
                var key = BookTextNormalizer.CompositeKey(
                    group.Metadata.Title, group.Metadata.Author, group.Metadata.Language);

                if (existingKeys.Contains(key))
                    dbDuplicates.Add(ToSkipped(group,
                        "A book with the same Title, Author, and Language already exists in the catalog."));
                else
                    newGroups.Add(group);
            }

            var allSkipped = batchDuplicates.Concat(dbDuplicates).ToList();

            // Short-circuit: every book was already in the catalog.
            if (newGroups.Count == 0)
                return new BulkUploadBooksResponse(0, allSkipped.Count, [], allSkipped);

            // ── Phase 4: Save files concurrently (new books only) ─────────────────
            // Each book saves its 3 files in parallel; all books run in parallel.
            var saveTasks = newGroups
                .Select(group => SaveBookFilesAsync(group, cancellationToken))
                .ToList();

            SavedFileSet[] savedResults;
            try
            {
                savedResults = await Task.WhenAll(saveTasks);
            }
            catch
            {
                // Compensate: delete only the files that were actually written.
                var partialPaths = saveTasks
                    .Where(t => t.IsCompletedSuccessfully)
                    .SelectMany(t => t.Result.AllPaths)
                    .ToList();
                await CleanupFilesAsync(partialPaths, cancellationToken);
                throw;
            }

            // ── Phase 5: Create entities + bulk insert ────────────────────────────
            try
            {
                var entities = savedResults
                    .Select(r =>
                    {
                        var book = new BookAggregate(
                            id:                  Guid.NewGuid(),
                            title:               r.Group.Metadata.Title.Trim(),
                            author:              r.Group.Metadata.Author.Trim(),
                            description:         r.Group.Metadata.Description.Trim(),
                            coverImageUrl:       r.CoverImageUrl,
                            language:            r.Group.Metadata.Language.Trim(),
                            categoryId:          r.Group.Metadata.CategoryId,
                            canonicalPdfUrl:     r.PdfUrl,
                            canonicalWordDocUrl: r.WordDocUrl);

                        var listing = CreateLibraryListing(book.Id, library.Id, r.Group.Metadata, r.PdfUrl);

                        return (Book: book, Listing: listing, Saved: r);
                    })
                    .ToList();

                var books = entities.Select(e => e.Book).ToList();

                // Listings are staged (not yet saved) here so that BulkInsertAsync's
                // internal SaveChangesAsync call below commits books and listings
                // together in one atomic transaction — both share the same DbContext.
                foreach (var entity in entities)
                    await _listingRepository.AddAsync(entity.Listing, cancellationToken);

                await _bookRepository.BulkInsertAsync(books, cancellationToken);

                var uploadResults = entities
                    .Select(e => new BookUploadResult(
                        e.Book.Id,
                        e.Book.Title,
                        e.Book.CoverImageUrl,
                        e.Saved.PdfUrl,
                        e.Saved.WordDocUrl,
                        e.Listing.Id,
                        e.Listing.Price,
                        e.Listing.Stock,
                        e.Listing.Format))
                    .ToList();

                return new BulkUploadBooksResponse(books.Count, allSkipped.Count, uploadResults, allSkipped);
            }
            catch
            {
                // DB failed — delete every file we saved during Phase 4.
                var allPaths = savedResults.SelectMany(r => r.AllPaths).ToList();
                await CleanupFilesAsync(allPaths, cancellationToken);
                throw;
            }
        }

        // Bulk uploads don't collect a physical condition, so newly catalogued
        // physical stock defaults to New. Digital listings reuse the just-uploaded
        // canonical PDF as their asset rather than requiring a separate upload.
        private static ListingAggregate CreateLibraryListing(
            Guid bookId,
            Guid libraryId,
            BookUploadMetadata metadata,
            string canonicalPdfUrl) =>
            metadata.Format switch
            {
                ListingFormat.Digital => ListingAggregate.CreateDigitalForLibrary(
                    id: Guid.NewGuid(),
                    bookId: bookId,
                    libraryId: libraryId,
                    price: metadata.Price,
                    customDigitalAssetUrl: canonicalPdfUrl),

                ListingFormat.Physical => ListingAggregate.CreateForLibrary(
                    id: Guid.NewGuid(),
                    bookId: bookId,
                    libraryId: libraryId,
                    price: metadata.Price,
                    condition: BookCondition.New,
                    stock: metadata.Quantity),

                _ => throw new DomainException($"Unsupported listing format: {metadata.Format}."),
            };

        // ── Helpers ──────────────────────────────────────────────────────────────

        /// <summary>
        /// Removes books from the batch that share a normalized (Title, Author, Language) key,
        /// keeping the first occurrence and reporting the rest as skipped.
        /// </summary>
        private static (List<BookUploadFileGroup> Unique, List<SkippedBookResult> Duplicates)
            DeduplicateWithinBatch(IReadOnlyList<BookUploadFileGroup> books)
        {
            var seen     = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var unique   = new List<BookUploadFileGroup>(books.Count);
            var skipped  = new List<SkippedBookResult>();

            foreach (var group in books)
            {
                var key = BookTextNormalizer.CompositeKey(
                    group.Metadata.Title, group.Metadata.Author, group.Metadata.Language);

                if (seen.Add(key))
                    unique.Add(group);
                else
                    skipped.Add(ToSkipped(group, "Duplicate entry within the uploaded batch."));
            }

            return (unique, skipped);
        }

        private static SkippedBookResult ToSkipped(BookUploadFileGroup group, string reason) =>
            new(group.FolderName, group.Metadata.Title, group.Metadata.Author,
                group.Metadata.Language, reason);

        private async Task<SavedFileSet> SaveBookFilesAsync(
            BookUploadFileGroup group,
            CancellationToken cancellationToken)
        {
            var coverTask = _storageService.SaveCoverImageAsync(group.CoverImage, cancellationToken);
            var pdfTask   = _storageService.SavePdfAsync(group.PdfFile,          cancellationToken);
            var wordTask  = _storageService.SaveWordDocAsync(group.WordFile,      cancellationToken);

            await Task.WhenAll(coverTask, pdfTask, wordTask);

            return new SavedFileSet(group, await coverTask, await pdfTask, await wordTask);
        }

        private async Task CleanupFilesAsync(IEnumerable<string> paths, CancellationToken cancellationToken)
            => await Task.WhenAll(paths.Select(p => SafeDeleteAsync(p, cancellationToken)));

        private async Task SafeDeleteAsync(string path, CancellationToken cancellationToken)
        {
            try
            {
                await _storageService.DeleteAsync(path, cancellationToken);
            }
            catch (Exception ex)
            {
                Logger.LogWarning(ex, "Failed to delete orphaned file: {Path}", path);
            }
        }

        private sealed record SavedFileSet(
            BookUploadFileGroup Group,
            string CoverImageUrl,
            string PdfUrl,
            string WordDocUrl)
        {
            public IEnumerable<string> AllPaths => [CoverImageUrl, PdfUrl, WordDocUrl];
        }
    }
}
